### ISSUE TITLE
gazebo seg fault error

### ISSUE THREAD

**Issue by kaviyachandran** [matthias-mayr/Cartesian-Impedance-Controller#3]
Hi Matthias,
Thank you for the controller. I am trying to use it with IIWA. when I launch gazebo with the impedance controller with the command 'roslaunch iiwa_gazebo iiwa_gazebo.launch controller:=CartesianImpedance_trajectory_controller', I get seg fault and the process dies. I am using ros-noetic.

![error_controller](https://user-images.githubusercontent.com/8038958/211522963-a56d00d2-e31a-42f8-9ba3-b4ebb69eb521.png)

Do you have any inputs on what might be causing the issue? 

Thank you

**Comment by matthias-mayr** [comment]
Great to to see the interest.

Assuming that you use `iiwa_ros`, you most likely are facing the same issue as @anubhav-dogra in #1. Right now `iiwa_ros` has an inconsistent build configuration.

The whole setup needs to be built without any `SIMD` instructions. That also includes the `iiwa_ros` dependencies.
If you've followed the latest build instructions, as a last step [these changes in needs to be applied.](https://github.com/epfl-lasa/iiwa_ros/pull/97/commits/47f6684c84b04cdf51f33ea92dc40d9ec7bf83db). If you use the real robot with it, make sure to build the `FRI` lib without `SIMD` as well.
You can read a bit more [in the other issue](https://github.com/matthias-mayr/Cartesian-Impedance-Controller/issues/1#issuecomment-1373909790).

Let me know if that fixed the issue.

**Comment by anubhav-dogra** [comment]
Try using the commands to upgrade your system first with ` sudo apt update` and `sudo apt upgrade` which removed the `gzserver` error in my case. I'm using ROS `Noetic` just to clarify.
This is followed by instructions or steps mentioned by @matthias-mayr in the coment above for the perfect gazebo simulation using `iiwa_ros` and `CartesianImpedance_trajectory_controller`.

**Comment by kaviyachandran** [comment]
Hi Matthias, 

Thanks for your reply.  I want the controller for a different robot so I am working on adapting it to my requirements. I will cite your work for sure :). 

One more question, are you using the latest version of RBDyn (updated on Nov 22, 2022)?.   You can close this issue.

**Comment by matthias-mayr** [comment]
Great to hear. Do you have something else than a Panda or iiwa? In principal it should work with any torque-controlled robot, but I am just aware of those two.

> I was building RBDyn and other dependencies with -DCMAKE_CXX_FLAGS="-march=native -faligned-new" . I was following iiwa_ros repo. When I rebuilt without these flags, the error is gone. I am closing this issue.

Yes, that caused us a lot of trouble as well. It's also not really apparent why it crashes until you know.

**Comment by kaviyachandran** [comment]
> 

I am working on an end effector impedance controller for PR2

**Comment by matthias-mayr** [comment]
hm. Does the PR2 have a joint torque interface? If it is position or velocity-controlled, you'd probably want to use this repo: https://github.com/fzi-forschungszentrum-informatik/cartesian_controllers

**Comment by kaviyachandran** [comment]
Thank you Mathias. I will check it out :)
