### ISSUE TITLE
Controller manager freezing when loading the controller

### ISSUE THREAD

**Issue by LuukvandenBent** [matthias-mayr/Cartesian-Impedance-Controller#7]
Hi Matthias, great work! I am trying to run the controller on a Franka Emika Panda/FR3 with moveit, i followed the installation instructions but the controller manager freezes when it tries to load the controller. Sorry if this is not a problem directly with your controller, but something on my end. Do you have any idea what causes this? I think https://answers.ros.org/question/284099/controller-spawner-stuck-while-loading/ is related, and it seems to be something about a multi-threaded spinner in the hw iface node, causing a deadlock.

**Comment by LuukvandenBent** [comment]
I found the problem... In the configuration file, the robot_description was set to the default: /robot_description. But I am running everything under a different namespace; so it should have been /{ns}/robot_description. In hindsight this was obvious since the last info message was about loading the robot description.

**Comment by matthias-mayr** [comment]
Great to hear that the controller could be useful for you.

Maybe it would actually be a bit more user-friendly to fail after some 20 seconds or so.

In any case, feel free to open other issues or pull request if you find something unintuitive.
