### ISSUE TITLE
Integration with Dart simulator

### ISSUE THREAD

**Issue by anubhav-dogra** [matthias-mayr/Cartesian-Impedance-Controller#9]
hey Matthias,
As you have mentioned that this library can be integrated with dart simulator. I am very new to dart as I have just started tutorials. 
Can you throw some light how do I integrate this library with dart simulator? 

Secondly:
I want to use iiwa_ros package with dart simulator using CI controller. Only selecting <args="physics" default="dart"/> in gazebo launch would not work right?

**Comment by matthias-mayr** [comment]
Do you want to use (1) DART standalone as a C++ library **or** use (2) DART as a physics engine inside Gazebo?

If you want to do (1), I can probably share some code from one of my students.

If it's (2), you would have to compile [Gazebo from source](https://classic.gazebosim.org/tutorials?tut=install_from_source&ver=4.0&cat=install). I did that once & it's doable if 
one has some experience with code compilation.
However you would not need to change anything w.r.t. to the controller configuration.

**Comment by anubhav-dogra** [comment]
Many Thanks @matthias-mayr for your quick response. 
I am really interested and would like to try (1), can you please share some?  my email is anubhav.dogra@warwick.ac.uk

**Comment by matthias-mayr** [comment]
I took a look. It's a bit less straight forward than expected.
It is written against [robot_dart](https://github.com/resibots/robot_dart) and not directly against DART. (On the other hand, that's of course what one would do anyway)
It uses an older version of this controller library and would need some changes and it of course uses our robot setup. It's goal is also to be a drop-in replacement for Gazebo for some experiments. Saying that it publishes to and subscribes the same ROS topics as the ROS controller would do.

**Comment by matthias-mayr** [comment]
I am assuming that this is answered. Feel free to re-open it if there's anything else.
